# Use S3 or local storage
USE_S3: True

# Directory paths (local)
base_dir: "../s3_bucket"
input_data_path: "../s3_bucket/s3_input"
intermediate_output_path: "../s3_bucket/s3_intermediate"
output_path: "../s3_bucket/s3_output"
misc_output_path: "../s3_bucket/s3_misc_output"
checkpoint_path: "../s3_bucket/s3_checkpoint"

# S3 folder names
s3_input_prefix: "idd-ai-pl-tagging-bucket_input"
s3_intermediate_prefix: "idd-ai-pl-tagging-bucket_intermediate"
s3_output_prefix: "idd-ai-pl-tagging-bucket_output"
s3_misc_output_prefix: "idd-ai-pl-tagging-bucket_misc_output"
s3_checkpoint_prefix: "idd-ai-pl-tagging-bucket_checkpoint"

PDF_URL: "../public/assets/PDF/File Format Guide for SFW and Sector File.pdf"

course_data_columns:
  - "Course Reference Number"
  - "Course Title"
  - "Skill Title"
  - "About This Course"
  - "What You'll Learn"

course_descr_cols:
  - "Course Reference Number"
  - "Course Title"
  - "About This Course"
  - "What You'll Learn"

process_choices:
  - "HR (Human Resource)"
  - "FS (Food Services)"
  - "FS (Financial Services)"
  - "FM (Food Manufacturing Services)"
  - "AIR (Air Transport Services)"
  - "BIO (BioPharmaceuticals Manufacturing Services)"
  - "BUILT (Built Environment Services)"
  - "EC (Energy and Chemicals Services)"
  - "ENG (Engineering Services)"
  - "ENV (Environmental Services)"
  - "HC (Healthcare Services)"
  - "LOG (Logistics Services)"
  - "MAR (Marine and Offshore Services)"
  - "PUB (Public Transport Services)"
  - "SEA (Sea Transport Services)"
  - "SEC (Security Services)"
  - "SOC (Social Service Services)"
  - "WATER (Water Management Services)"
  - "TRADE (Wholesale Trade Services)"

process_alias_mapping:
  HR:
    - "Human Resource"
  FS:
    - "Food Services"
    - "Financial Services"
  FM:
    - "Food Manufacturing Services"
  AIR:
    - "Air Transport Services"
  BIO:
    - "BioPharmaceuticals Manufacturing Services"
  BUILT:
    - "Built Environment Services"
  EC:
    - "Energy and Chemicals Services"
  ENG:
    - "Engineering Services"
  ENV:
    - "Environmental Services"
  HC:
    - "Healthcare Services"
  LOG:
    - "Logistics Services"
  MAR:
    - "Marine and Offshore Services"
  PUB:
    - "Public Transport Services"
  SEA:
    - "Sea Transport Services"
  SEC:
    - "Security Services"
  SOC:
    - "Social Service Services"
  WATER:
    - "Water Management Services"
  TRADE:
    - "Wholesale Trade Services"

input_validation_sector_config:
  "Human Resource": "HR"
  "Food Services": "FS"
  "Financial Services": "FS"
  "Food Manufacturing": "FM"
  "Air Transport": "AIR"
  "BioPharmaceuticals Manufacturing": "BIO"
  "Built Environment": "BUILT"
  "Energy and Chemicals": "EC"
  "Engineering Services": "ENG"
  "Environmental Services": "ENV"
  "Healthcare": "HC"
  "Logistics": "LOG"
  "Marine and Offshore": "MAR"
  "Public Transport": "PUB"
  "Sea Transport": "SEA"
  "Security": "SEC"
  "Social Service": "SOC"
  "Water Management": "WATER"
  "Wholesale Trade": "TRADE"
