# Use S3 or local storage
USE_S3: False  # Change to "true" to use S3
s3_bucket_name: "idd-ai-pl-tagging-bucket"
aws_region: "ap-southeast-1"

# Directory paths (local)
base_dir: "../s3_bucket"
input_data_path: "../s3_bucket/s3_input"
intermediate_output_path: "../s3_bucket/s3_intermediate"
output_path: "../s3_bucket/s3_output"
misc_output_path: "../s3_bucket/s3_misc_output"
checkpoint_path: "../s3_bucket/s3_checkpoint"

# S3 folder names 
s3_input_prefix: "s3_input"
s3_intermediate_prefix: "s3_intermediate"
s3_output_prefix: "s3_output"
s3_misc_output_prefix: "s3_misc_output"
s3_checkpoint_prefix: "s3_checkpoint"

PDF_URL: "../public/assets/PDF/File Format Guide for SFW and Sector File.pdf"

course_data_columns:
  - "Course Reference Number"
  - "Course Title"
  - "Skill Title"
  - "About This Course"
  - "What You'll Learn"

course_descr_cols:
  - "Course Reference Number"
  - "Course Title"
  - "About This Course"
  - "What You'll Learn"

process_choices:
  - "HR (Human Resource)"
  - "FS (Food Services)"
  - "FS (Financial Services)"

process_alias_mapping:
  HR:
    - "Human Resource"
  FS:
    - "Food Services"
    - "Financial Services"

input_validation_sector_config:
  "Human Resource": "HR"
  "Food Services": "FS"
  "Financial Services": "FS"
