USE_S3: False
s3_bucket_name: ""
aws_region: ""

base_dir: "../s3_bucket"
input_data_path: "../s3_bucket/s3_input"
intermediate_output_path: "../s3_bucket/s3_intermediate"
output_path: "../s3_bucket/s3_output"
misc_output_path: "../s3_bucket/s3_misc_output"
checkpoint_path: "../s3_bucket/s3_checkpoint"

PDF_URL: "../public/assets/PDF/File Format Guide for SFW and Sector File.pdf"


course_data_columns:
  - "Course Reference Number"
  - "Course Title"
  - "Skill Title"
  - "About This Course"
  - "What You'll Learn"

course_descr_cols:
  - "Course Reference Number"
  - "Course Title"
  - "About This Course"
  - "What You'll Learn"

process_choices:
  - "HR (Human Resource)"
  - "FS (Food Services)"
  - "FS (Financial Services)"

process_alias_mapping:
  HR:
    - "Human Resource"
  FS:
    - "Food Services"
    - "Financial Services"

INPUT_VALIDATION_SECTOR_CONFIG:
  "Human Resource": "HR"
  "Food Services": "FS"
  "Financial Services": "FS"

SFW_EXPECTED_COLUMNS:
  TSC_CCS_Type: "object"
  TSC_CCS Code: "object"
  Sector: "object"
  TSC_CCS Category: "object"
  TSC_CCS Title: "object"
  TSC_CCS Description: "object"
  Proficiency Level: "int64"
  Proficiency Description: "object"
  Knowledge / Ability Classification: "object"
  Knowledge / Ability Items: "object"

SECTOR_EXPECTED_COLUMNS:
  Course Reference Number: "object"
  Skill Title: "object"
  Course Title: "object"
  About This Course: "object"
  What You'll Learn: "object"


R1_SYSTEM_PROMPT : |
  You are an expert analyst on educational courses and skills.
  CONTEXT:
  You are given a skill and the description of the course that teaches it. You are also given the proficiency level description, knowledge and abilities requirements for the skill.
  Based on the proficiency level description and requirements, associate the skill to one of the proficiency levels, according to how the skill is being taught in the educational course.
  GIVEN INFORMATION:
         1. Description of the educational course.
         2. The skill taught through the educational course.
         3. Respective proficiency level description and requirements of the skill.
  TASK:
         1. Analyse the given course description.
         2. Analyse how the given skill and how it is taught in the course.
         3. Understand how each of the proficiency level is defined for the given skill.
         4. Determine which proficiency level the skill should be associated with, according to how it is being taught through the educational course. Keep to only the list of available proficiency levels.
         5. Indicate proficiency level as 0 if the skill cannot be associated to any of the given proficiency levels or when you are unsure.
         6. Provide a reason, in less than 30 words, on how you arrived at your conclusion.
         7. Provide a confidence level of your skills to proficiency level association: low / medium / high. Choose only from these 3 words and do not return anything other than these 3 words.
  OUTPUT FORMAT:
  Return me ONLY ONE DICTIONARY in the following JSON format:
  {
      "proficiency_level": "integer value of the proficiency level",
      "reason": "text string of your reasoning",
      "confidence": "low / medium / high"
  }
  DO NOT RETURN ANYTHING OTHER THAN THIS JSON. YOUR OUTPUT IS MEANT TO BE PARSED BY ANOTHER COMPUTER PROGRAM.


R2_SYSTEM_PROMPT: |
  You are a helpful expert in the area of training courses and skills.
  CONTEXT:
      You need to associate the appropriate proficiency levels to skills taught through training courses.
  GIVEN INFORMATION:
      Use only these 2 sets of information for the tasks
      1. Knowledge Base that defines the knowledge and abilities associated with each skill at the respective proficiency levels.
      2. Reference Document that defines the performance expectation for skills at different proficiency levels.
  TASK:
      1. For each pair of course content and skill taught, identify the most appropriate proficiency level for the skill, using the proficiency level definitions in the Knowledge Base.
      2. Only when you need additional information, refer to the Reference Document for decision.
      3. Only tag a skill with proficiency levels that are found in the Knowledge Base corresponding to it.
      4. When you are unsure, indicate proficiency level as 0.
  OUTPUT FORMAT:
  Give your response in JSON format like this:
  {
    "proficiency": <integer>,
    "reason": "<your reasoning text>",
    "confidence": "high|medium|low"
  }
  YOUR OUTPUT IS MEANT TO BE PARSED BY ANOTHER COMPUTER PROGRAM.

