USE_S3: False
s3_bucket_name: ""
aws_region: ""

base_dir: "../s3_bucket"
input_data_path: "../s3_bucket/s3_input"
intermediate_output_path: "../s3_bucket/s3_intermediate"
output_path: "../s3_bucket/s3_output"
misc_output_path: "../s3_bucket/s3_misc_output"
checkpoint_path: "../s3_bucket/s3_checkpoint"

PDF_URL: "../public/assets/PDF/File Format Guide for SFW and Sector File.pdf"


course_data_columns:
  - "Course Reference Number"
  - "Course Title"
  - "Skill Title"
  - "About This Course"
  - "What You'll Learn"

course_descr_cols:
  - "Course Reference Number"
  - "Course Title"
  - "About This Course"
  - "What You'll Learn"

process_choices:
  - "HR (Human Resource)"
  - "FS (Food Services)"
  - "FS (Financial Services)"

process_alias_mapping:
  HR:
    - "Human Resource"
  FS:
    - "Food Services"
    - "Financial Services"

INPUT_VALIDATION_SECTOR_CONFIG:
  "Human Resource": "HR"
  "Food Services": "FS"
  "Financial Services": "FS"

