name: Docker Build & Streamlit Health Check

on:
  push:
    branches: [deploy]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t jstgt-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 --name streamlit-test jstgt-app
        # Wait up to 40 seconds for the app to start
        for i in {1..10}; do
          sleep 4
          if curl -f http://localhost:8501/_stcore/health; then
            echo "Streamlit is healthy!"
            exit 0
          fi
          echo "Waiting for Streamlit to become healthy..."
        done
        echo "Streamlit app failed to start in time."
        docker logs streamlit-test
        exit 1

    - name: Clean up
      run: docker stop streamlit-test
